/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIScorePanel: typeof import('./../components/business/AIScorePanel.vue')['default']
    BarChart: typeof import('./../components/chart/BarChart.vue')['default']
    BaseButton: typeof import('./../components/base/BaseButton.vue')['default']
    BaseDatePicker: typeof import('./../components/base/BaseDatePicker.vue')['default']
    BaseForm: typeof import('./../components/base/BaseForm.vue')['default']
    BaseInput: typeof import('./../components/base/BaseInput.vue')['default']
    BaseModal: typeof import('./../components/base/BaseModal.vue')['default']
    BasePagination: typeof import('./../components/base/BasePagination.vue')['default']
    BaseSelect: typeof import('./../components/base/BaseSelect.vue')['default']
    BaseTable: typeof import('./../components/base/BaseTable.vue')['default']
    BaseUpload: typeof import('./../components/base/BaseUpload.vue')['default']
    CodeEditor: typeof import('./../components/business/CodeEditor.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    EmptyState: typeof import('./../components/common/EmptyState.vue')['default']
    ErrorState: typeof import('./../components/common/ErrorState.vue')['default']
    FileUploader: typeof import('./../components/business/FileUploader.vue')['default']
    GradingRuleForm: typeof import('./../components/business/GradingRuleForm.vue')['default']
    LineChart: typeof import('./../components/chart/LineChart.vue')['default']
    LoadingState: typeof import('./../components/common/LoadingState.vue')['default']
    Navbar: typeof import('./../components/layout/Navbar.vue')['default']
    NoPermission: typeof import('./../components/common/NoPermission.vue')['default']
    PageContainer: typeof import('./../components/layout/PageContainer.vue')['default']
    PageHeader: typeof import('./../components/layout/PageHeader.vue')['default']
    RadarChart: typeof import('./../components/chart/RadarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/layout/Sidebar.vue')['default']
    StatCard: typeof import('./../components/business/StatCard.vue')['default']
    TaskStatusBadge: typeof import('./../components/business/TaskStatusBadge.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
